INSERT INTO DEFAUTS (ID_DEFAUT,LIGNE,VOIE,NOMVOIE,LIGNE_VOIE,METRE,ANNEE_POSE,PROFIL_RAIL,VITESSE,GROUPE_UIC,RAYON_COURBE,TYPE_CLASSEMENT,EMPLACEMENT,TYPE_DEFAUT,ANNEE_DECOUVERTE,AGE) 

SELECT
	ID_DEFAUT AS ID_DEFAUT, 
	Ligne_Num	AS LIGNE,
	NOMVOIE AS VOIE,
	substr(nomvoie,1,case when instr(nomvoie,'(') = 0 THEN length(nomvoie) else instr(nomvoie,'(')-1 end) AS NOMVOIE,
	Ligne_num ||'-'||substr(nomvoie,1,case when instr(nomvoie,'(') = 0 THEN length(nomvoie) else instr(nomvoie,'(')-1 end) AS LIGNE_VOIE,
	substr(pk_defaut,1,instr(pk_defaut,'+')-1)*1000 + substr(pk_defaut,instr(pk_defaut,'+')+1) AS METRE,
	ANNEE_POSE AS ANNEE_POSE,
	PROFIL_RAIL AS PROFIL_RAIL,
	VITESSE AS VITESSE,
	GROUPE_UIC AS GROUPE_UIC,
	RAYON_COURBE AS RAYON_COURBE,
	ID_TYPE_CLASSEMENT AS TYPE_CLASSEMENT,
	ID_TYPE_EMPLACEMENT AS EMPLACEMENT,
	ID_TYPE_DEFAUT AS TYPE_DEFAUT,
	ANNEE_DECOUVERTE AS ANNEE_DECOUVERTE,
	ANNEE_DECOUVERTE - ANNEE_POSE AS AGE
FROM
	DEF_PN_BIS
ORDER BY
	LIGNE_VOIE, PK_DEFAUT